#!/usr/bin/python

import json
import subprocess
import sys

indeces = []

for line in subprocess.check_output(["curl", "-sS", "localhost:9200/_cat/indices?v"]).split("\n"):
    atoms = line.split()

    if len(atoms) < 3 or atoms[2] == "index" or atoms[2] == ".kibana":
        continue

    indeces.append(atoms[2])

indeces.sort(reverse=True)
lines      = []
lineNumber = 0

while True:
    # Note: Don't use format due to empty object {} in JSON query
    index = json.loads(subprocess.check_output(["curl", "-sS", "-XPOST", "localhost:9200/{}/_search".format(indeces[0]), "-d",
                                                '{"query": {"match_all": {}}, "from": %d, "size": 10000}' % (len(lines))]))

    try:
        lines.append(index["hits"]["hits"])
    except KeyError:
        sys.exit("No hits in output: {}".format(str(index)))

    if len(index["hits"]["hits"]) < 10000:
        break

lines.reverse()
sys.exit(str(len(lines)))

for line in lines:
    line = line["_source"]
    print "{}:{}:{}:{}".format(line["host"], line["source"], line["@timestamp"], line["data"])
