#!/usr/bin/python

import json
import subprocess
import sys

indeces = []

for line in subprocess.check_output(["curl", "-sS", "localhost:9200/_cat/indices?v"]).split("\n"):
    atoms = line.split()

    if len(atoms) < 3 or atoms[2] == "index" or atoms[2] == ".kibana":
        continue

    indeces.append(atoms[2])

indeces.sort(reverse=True)
lines      = []
lineNumber = 0
index = json.loads(subprocess.check_output(["curl", "-sS", "-XGET", "localhost:9200/{}/_search?scroll=1m".format(indeces[0]),
                                            "-d", '{"query": {"match_all": {}}, size: 10000}']))
while True:
    try:
        if len(index["hits"]["hits"]) == 0:
            break
    except KeyError:
        sys.exit("Failed to find 'hits' in response: " + str(index))

    lines.append(index["hits"]["hits"])
    print str(len(index["hits"]["hits"])) + " " + index["hits"]["hits"][0]["_source"]["@timestamp"]
    scroll_id = index["_scroll_id"]

    # Note: Don't use format due to {} in JSON querys
    index = json.loads(subprocess.check_output(["curl", "-sS", "-XGET", "localhost:9200/_search/scroll",
                                                "-d", '{"scroll" : "1m", "scroll_id" : "%s"}' % scroll_id]))

subprocess.check(["curl", "-sS", "-XDELETE", "localhost:9200/_search/scroll", "-d", '{"scroll_id" : ["%s"]}' % scroll_id])
lines.reverse()
sys.exit(str(len(lines)))

for line in lines:
    line = line["_source"]
    print "{}:{}:{}:{}".format(line["host"], line["source"], line["@timestamp"], line["data"])
